CREATE TABLE IF NOT EXISTS auto
(
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(45) NOT NULL,
    UNIQUE INDEX UX_name (name)
);

CREATE TABLE IF NOT EXISTS models
(
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(45) NOT NULL,
    auto_id INT UNSIGNED NOT NULL,
    UNIQUE INDEX UX_name (name),
    FOREIGN KEY FK_auto (auto_id) REFERENCES auto (id)
);